### ISSUE TITLE
Couldn't get the script to work. I'm very new to this

### ISSUE THREAD

**Issue by sebbeee** [IceM4nn/mirrorscript-v2#1]
root@kali:~/mirrorscript-v2# python3 mirrorscript-v2.py -v -https -src
#
# Mirrorscripts-v2 - By Hazmirul Afiq
# Automatically select the best Kali mirror and apply the configuration
# https://github.com/IceM4nn/mirrorscript-v2
# https://www.metahackers.pro/speed-kali-linux-update/
#

[-] Checking if 'apt-transport-https' package is installed.
	- apt-transport-https is installed

[+] Getting mirror list ...
[+] Found a lists of mirrors:
	- https://mirrors.dotsrc.org/kali
	- https://ftp.acc.umu.se/mirror/kali.org/kali
	- https://ftp.halifax.rwth-aachen.de/kali
	- https://mirror.neostrada.nl/kali
	- https://ftp2.nluug.nl/os/Linux/distr/kali
	- https://ftp1.nluug.nl/os/Linux/distr/kali
	- https://mirror.karneval.cz/pub/linux/kali
	- https://archive-4.kali.org/kali
	- https://kali.download/kali
	- https://mirrors.ocf.berkeley.edu/kali
	- https://hlzmel.fsmg.org.nz/kali
	- https://wlglam.fsmg.org.nz/kali

[+] Checking mirrors ...
[+] Finding the best latency
Traceback (most recent call last):
  File "mirrorscript-v2.py", line 136, in <module>
    average = p[0].strip().splitlines()[7].split('=')[1].split('/')[1]
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mirrorscript-v2.py", line 140, in <module>
    if not ask("\t[!] Something went wrong. would you like to try again [y] or [n].",'y'):
  File "mirrorscript-v2.py", line 42, in ask
    choice = raw_input(question + " Default [" + default + "]: ").lower()
NameError: name 'raw_input' is not defined
root@kali:~/mirrorscript-v2#

**Comment by IceM4nn** [comment]
Ohh my.. the script is broken. I'm apologize not noticing it earlier. Thanks for submitting this bug. I'll fix it asap.

**Comment by IceM4nn** [comment]
Please try again with the new patch. Let me know if there's any bugs.
```
# cd mirrorscript-v2
# git pull
# python3 mirrorscript-v2.py -v -https
```

**Comment by sebbeee** [comment]
Hello! Tried it again, but i got this;

root@kali:~# cd mirror*
root@kali:~/mirrorscript-v2# git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 1), reused 3 (delta 1), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/IceM4nn/mirrorscript-v2
   ef582cb..cee25cc  master     -> origin/master
Updating ef582cb..cee25cc
error: Your local changes to the following files would be overwritten by merge:
	mirrorscript-v2.py
Please commit your changes or stash them before you merge.
Aborting
root@kali:~/mirrorscript-v2# python3 mirrorscript-v2.py -v -https
#
# Mirrorscripts-v2 - By Hazmirul Afiq
# Automatically select the best Kali mirror and apply the configuration
# https://github.com/IceM4nn/mirrorscript-v2
# https://www.metahackers.pro/speed-kali-linux-update/
#

[-] Checking if 'apt-transport-https' package is installed.
	- apt-transport-https is installed

[+] Getting mirror list ...
[+] Found a lists of mirrors:
	- https://mirrors.dotsrc.org/kali
	- https://ftp.acc.umu.se/mirror/kali.org/kali
	- https://ftp.halifax.rwth-aachen.de/kali
	- https://mirror.neostrada.nl/kali
	- https://ftp2.nluug.nl/os/Linux/distr/kali
	- https://ftp1.nluug.nl/os/Linux/distr/kali
	- https://mirror.karneval.cz/pub/linux/kali
	- https://archive-4.kali.org/kali
	- https://kali.download/kali
	- https://mirrors.ocf.berkeley.edu/kali
	- https://hlzmel.fsmg.org.nz/kali
	- https://wlglam.fsmg.org.nz/kali

[+] Checking mirrors ...
[+] Finding the best latency
Traceback (most recent call last):
  File "mirrorscript-v2.py", line 136, in <module>
    average = p[0].strip().splitlines()[7].split('=')[1].split('/')[1]
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mirrorscript-v2.py", line 140, in <module>
    if not ask("\t[!] Something went wrong. would you like to try again [y] or [n].",'y'):
  File "mirrorscript-v2.py", line 42, in ask
    choice = raw_input(question + " Default [" + default + "]: ").lower()
NameError: name 'raw_input' is not defined
root@kali:~/mirrorscript-v2#

**Comment by IceM4nn** [comment]
Please delete the folder. and re-clone the repo.
```
# cd ~ 
# rm -rf ~/mirrorscript-v2
# git clone https://github.com/IceM4nn/mirrorscript-v2.git
# cd mirrorscript-v2
# python3 mirrorscript-v2.py -v -https
```

**Comment by sebbeee** [comment]
I reinstalled Kali and it seems to be working well now. This is what's in my sources.list file now. should i leave it or should i remove something ?;

# 

# deb cdrom:[Debian GNU/Linux 2019.2 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20190508-08:43]/ kali-last-snapshot contrib main non-free

#deb cdrom:[Debian GNU/Linux 2019.2 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20190508-08:43]/ kali-last-snapshot contrib main non-free

#deb http://http.kali.org/kali kali-rolling main non-free contrib
# deb-src http://http.kali.org/kali kali-rolling main non-free contrib

# This system was installed using small removable media
# (e.g. netinst, live or single CD). The matching "deb cdrom"
# entries were disabled at the end of the installation process.
# For information about how to configure apt package sources,
# see the sources.list(5) manual.

# Autogenerated script by MirrorScripts-V2
deb https://kali.download/kali kali-rolling main contrib non-free
#deb-src https://kali.download/kali kali-rolling main contrib non-free

**Comment by IceM4nn** [comment]
Remove all except the line Autogenerated script and below

**Comment by sebbeee** [comment]
Great! Thanks!
Sources.list looks like this now ;
"
# Autogenerated script by MirrorScripts-V2
deb https://kali.download/kali kali-rolling main contrib non-free
#deb-src https://kali.download/kali kali-rolling main contrib non-free
"

But I am still getting pretty low download speeds when i run apt update and then apt upgrade. Maximum around 40kb/s. Any ideas? I know it's not related with the script but the threads I read on the subject mentioned it should improve after choosing a mirror that was closer to me.
