### ISSUE TITLE
 Couldn't get the script to work.

### ISSUE THREAD

**Issue by Mati018** [IceM4nn/mirrorscript-v2#2]
#
# Mirrorscripts-v2 - By Hazmirul Afiq
# Automatically select the best Kali mirror and apply the configuration
# https://github.com/IceM4nn/mirrorscript-v2
# https://www.metahackers.pro/speed-kali-linux-update/
#

[-] Checking if 'apt-transport-https' package is installed.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 194, in __getitem__
    return self._weakref[key]
  File "/usr/lib/python3.6/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: 'apt-transport-https'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mirrorscript-v2.py", line 100, in <module>
    if cache[package].is_installed:
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 204, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'apt-transport-https'"

**Comment by IceM4nn** [comment]
Hmm.. can you first try install `apt-transport-https` manually? Run the following command: 
```
sudo apt install apt-transport-https -y
``` 
then retry the script.. let me know if that works.

**Comment by Mati018** [comment]
yes i have installed `apt-trensport-https` manually. its not working

**Comment by IceM4nn** [comment]
I'm sorry, I couldn't reproduce your issue. If the package is already install, it shouldn't produce the same error. Can you provide more details?
