### ISSUE TITLE
facing error "Something went wrong. would you like to try again"

### ISSUE THREAD

**Issue by r1riyad** [IceM4nn/mirrorscript-v2#3]
By running this command "**python3 mirrorscript-v2.py -v -https -src**
" 
i m getting this error....ss below

![Screenshot_2020-07-17_23-11-25](https://user-images.githubusercontent.com/33262712/87812980-dc90c400-c882-11ea-9831-39f24660e4c1.png)

And by running only "**python3 mirrorscript-v2.py**"..... i am getting this
![Screenshot_2020-07-17_23-12-48](https://user-images.githubusercontent.com/33262712/87813099-0cd86280-c883-11ea-85d7-5068d8e8e4ca.png)
 Please fix this!! this is an awesome script. I used it earlier without issue...

**Comment by IceM4nn** [comment]
Hello there, thanks for submitting this issue. I think the host is probably down when performing latency checking. At the time I'm on a vacation, I'll push fix in monday..

**Comment by kni9ht** [comment]
By running this command "sudo python3 mirrorscript-v2.py -v -https -src"
i am getting an error 
![error](https://user-images.githubusercontent.com/55698799/109640848-fadbd380-7b76-11eb-85be-2b22c0b05e26.png)
:

**Comment by IceM4nn** [comment]
@r1riyad @kni9ht issue fixed. please try the new one.
