### ISSUE TITLE
when used the script run command (sudo python3 mirrorscript-v2.py -h)

### ISSUE THREAD

**Issue by ghost** [IceM4nn/mirrorscript-v2#6]
Traceback (most recent call last):
  File "/home/friday/mirrorscript-v2/mirrorscript-v2.py", line 3, in <module>
    import subprocess, requests, re, sys
ModuleNotFoundError: No module named 'requests'

**Comment by IceM4nn** [comment]
Install python requests module:
```
sudo pip3 install requests
```
